const DEFAULT_USER_EMAIL = 'example9@gmail.com'
const DEFAULT_USER_PASSWORD = '1234567'

module.exports = { 
    DEFAULT_USER_EMAIL: DEFAULT_USER_EMAIL,
    DEFAULT_USER_PASSWORD: DEFAULT_USER_PASSWORD 
};
